name: smart-vault-api-gateway

services: 
  auth-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
      - ${POSTGRES_PORT}:5432
  backend-api:
    build:
      context: .
    environment:
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      API_GATEWAY_ISSUER: ${API_GATEWAY_ISSUER}
      API_GATEWAY_AUDIENCE: ${API_GATEWAY_AUDIENCE}
      ALLOWED_ORIGIN: ${ALLOWED_ORIGIN}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      DATABASE_URL: ${DATABASE_URL}
#     volumes:
#       - auth-db-data:/var/lib/postgresql/data
# volumes:
#   auth-db-data:
