name: smart-vault-api-gateway

services: 
  auth-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
      - 5432:5432
#     volumes:
#       - auth-db-data:/var/lib/postgresql/data
# volumes:
#   auth-db-data:
