name: smart-vault-api-gateway

services: 
  auth-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports: 
      - ${POSTGRES_PORT}:5432
  backend-api:
    build:
      context: .
    environment:
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      API_GATEWAY_ISSUER: ${API_GATEWAY_ISSUER}
      API_GATEWAY_AUDIENCE: ${API_GATEWAY_AUDIENCE}
      ALLOWED_ORIGIN: ${ALLOWED_ORIGIN}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    depends_on: 
      auth-db:
        condition: service_healthy
        restart: true
#     volumes:
#       - auth-db-data:/var/lib/postgresql/data
# volumes:
#   auth-db-data:
